# Generated by Django 3.0.8 on 2020-07-17 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20200716_2244'),
    ]

    operations = [
    ]
