# Generated by Django 3.0.8 on 2020-07-17 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20200717_0431'),
    ]

    operations = [
    ]
